#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Configuration
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-09-01
#	Description :	Set configuration to Configuration
#--------------------------------------------------------------------

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret key_lat
  longitude: !secret key_lon

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret key_ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon

  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob: !include customize_glob.yaml
  
config: 

# Enables the frontend

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

#http:
#  api_password: XPTO
#  trusted_networks:
#  - 192.168.2.140
#  ip_ban_enabled: True
#  login_attempts_threshold: 5

http:
  base_url: !secret key_base_url
#  server_port: 8123
  api_password: !secret key_api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
#  include:
#    entities:
#      - sensor.luis
#      - sensor.monica
#      - sensor.temperature_158d0001ab1740
#      - sensor.temperature_158d0001fa763c
#      - sensor.temp_anexo
#      - sensor.temp_rua__petra
#      - binary_sensor.door_window_sensor_158d0001d86c17
#      - binary_sensor.door_window_sensor_158d00018354d0
#      - binary_sensor.door_window_sensor_158d00015a954e
#      - switch.telheiro
#      - switch.anexo
#      - switch.anexo_rua
#      - switch.luz1
#      - switch.luz2
#      - switch.luz_petra
#      - light.gateway_light_34ce0088aff1
#      - light.gateway_light_7811dcdedcf1
#      - light.gateway_light_7811dcb3556e

# View all events in a logbook   
logbook:
  include:
    entities:
      - sensor.luis
      - sensor.monica
      - sensor.temperature_158d0001ab1740
      - sensor.temperature_158d0001fa763c
      - sensor.temp_anexo
      - sensor.temp_rua__petra
      - binary_sensor.door_window_sensor_158d0001d86c17
      - binary_sensor.door_window_sensor_158d00018354d0
      - binary_sensor.door_window_sensor_158d00015a954e
      - switch.telheiro
      - switch.anexo
      - switch.anexo_rua
      - switch.luz1
      - switch.luz2
      - switch.luz_petra
      - light.gateway_light_34ce0088aff1
      - light.gateway_light_7811dcdedcf1
      - light.gateway_light_7811dcb3556e

############
# INCLUDES #
############
group: !include groups.yaml
zone: !include zones.yaml
input_select: !include input_select.yaml
automation: !include automation.yaml
shell_command: !include shell_commands.yaml
proximity: !include_dir_merge_named proximity

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: 'pt'

logger:
#  default: error

weather:
  - platform: ipma
