#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Anexo
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-10-03
#	Description :	Set configuration to Anexo
#--------------------------------------------------------------------

homeassistant:

input_datetime:
  luz3:
    name: ON Anexo.
    has_time: true      
    initial: '08:00:00'
  luz4:
    name: OFF Anexo.
    has_time: true      
    initial: '19:00:00'

automation:

# Liga a luz do anexo pelo UI
  - alias: Liga luz do anexo de manha
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.luz3.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.anexo

# Desliga a luz do anexo pelo UI         
  - alias: Desliga anexo tarde
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.luz4.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.anexo

# Liga a luz do anexo quando há movimento e temos LUX inferior a 200
  - alias: Liga a luz do anexo quando há movimento e temo LUX inferior a 200
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e516b8
      to: 'on'
    condition:
      condition: numeric_state
      entity_id: sensor.illumination_158d0001e516b8
      below: '200'
    action:
      service: switch.turn_on  
      data:      
        entity_id: switch.anexo     

# Desliga a luz do anexo 5 minutos após o ultimo movimento e quando temos LUX inferior a 20
  - alias: Desliga a luz do anexo 5 minutos após o ultimo movimento e quando temos LUX inferior a 20
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e516b8
      to: 'off'
      for:
        minutes: 5
    condition:
      condition: numeric_state
      entity_id: sensor.illumination_158d0001e516b8
      below: '20'
    action:
      service: switch.turn_off
      data:
        entity_id: switch.anexo

###############################################################################
#                                                                             #
#                           D E S A T I V O S                                 #
#                                                                             #
###############################################################################
        
## Liga a luz do anexo das 07:01
#  - alias: Liga luz do anexo de manha
#    initial_state: true
#    trigger:
#      platform: time
#      at: '07:01'                         
#    action:
#      service: switch.turn_on                 
#      data:
#        entity_id: switch.anexo
#
## Desliga a luz do anexo às 19:00
#  - alias: Desliga anexo tarde
#    trigger:
#      platform: time
#      at: '18:59' 
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.anexo

#  - alias: Liga luz do anexo 5 minutos apos o nascer do sol
#    initial_state: true
#    trigger:
#      platform: sun
#      event: sunrise
#      offset: '00:05:00'                     
#    action:
#      service: switch.turn_on                 
#      data:
#        entity_id: switch.anexo
#
#  - alias: Desliga luz do anexo após por do sol
#    trigger:
#      platform: sun
#      event: sunset
#      offset: '+00:00:00'
#    condition:
#      condition: sun
#      before: sunset
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.anexo
#
#  - alias: Liga a luz á noite com o sensor de movimento.
##    initial_state: true
#    trigger:
#      platform: state
#      entity_id: binary_sensor.motion_sensor_158d0001e516b8
#      to: 'on'
#    condition:
#      condition: sun
#      after: sunset
##      before: sunrise
#    action:
#      service: switch.turn_on  
#      data:      
#        entity_id: switch.anexo
#
#  - alias: Desliga a luz do anexo após 2min sem movimento depois do por do sol e antes do nascer do sol.
##    initial_state: true
#    trigger:
#      platform: state
#      entity_id: binary_sensor.motion_sensor_158d0001e516b8
#      to: 'off'
#      for:
#        minutes: 2
#    condition:
#      condition: sun
#      after: sunset
#      before: sunrise
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.anexo    

### CRIA UM SENSOR MAS NO PAINEL SEMPRE QUE HA ALTERAÇÃO DE ESTADO ELE NÃO FICA AMARELO - NÃO ESTÁ EM USO ###
#sensor:
#  platform: template
#  sensors:
#    motion_anexo:
#      value_template: '{% if is_state("binary_sensor.motion_sensor_158d0001e516b8", "on") %} Sim {% else %} Não {%- endif %}'