#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Pilhas
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-04-30
#	Description :	Set configuration to pilhas
#--------------------------------------------------------------------

homeassistant:
input_boolean:

  battery_notifications:
    name: Notificações da bateria
    initial: 'on'
    icon: 'mdi:battery-charging-wireless'

sensor:

  - platform: template
    sensors:
      p_cozinha_battery_level:
        friendly_name: Porta cozinha
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d00018354d0.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d00018354d0.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      p_principal_battery_level:
        friendly_name: Porta principal
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d00015a954e.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d00015a954e.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      p_esquerda_battery_level:
        friendly_name: Porta esquerda
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d0001d399b1.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0001d399b1.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      p_direita_battery_level:
        friendly_name: Porta direita
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d0001d39ff1.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0001d39ff1.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}      

      p_portao_battery_level:
        friendly_name: Portão
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d0001d86c17.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0001d86c17.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}         

      p_anexo_battery_level:
        friendly_name: Mov. Anexo
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d0001e516b8.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d0001e516b8.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.motion_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.motion_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}             

      p_sala_battery_level:
        friendly_name: Mov. Sala
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d00015e8fdf.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d00015e8fdf.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.motion_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.motion_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %} 

      p_correio_battery_level:
        friendly_name: Mov. Correio
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d000152fc00.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d000152fc00.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.motion_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.motion_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}       

      p_botao_battery_level:
        friendly_name: Interruptor Anexo
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.switch_158d0001b86d3e.attributes.battery_level %}
            {{ states.binary_sensor.switch_158d0001b86d3e.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.switch.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.switch.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      p_interruptor_battery_level:
        friendly_name: Interruptor Cozinha
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.wall_switch_left_158d0001e0f91d.attributes.battery_level %}
            {{ states.binary_sensor.wall_switch_left_158d0001e0f91d.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.wall_switch_left.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.wall_switch_left.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}           

      p_temp1_battery_level:
        friendly_name: Temp. Carolina
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.sensor.temperature_158d0001ab1740.attributes.battery_level %}
            {{ states.sensor.temperature_158d0001ab1740.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.temperature.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.temperature.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      p_temp2_battery_level:
        friendly_name: Temp. Casa
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.sensor.temperature_158d0001fa763c.attributes.battery_level %}
            {{ states.sensor.temperature_158d0001fa763c.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.temperature.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.temperature.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      p_rua_battery_level:
        friendly_name: Mov. Rua
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d0001e51352.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d0001e51352.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.motion_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.motion_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      p_1andar_battery_level:
        friendly_name: Mov. Rua
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d0001e53332.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d0001e53332.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.motion_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.motion_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      p_portaanexo_battery_level:
        friendly_name: Porta anexo
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d0001b91cef.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0001b91cef.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}       

  - platform: mqtt
    name: Bateria Tlm Luis
    state_topic: "zanzito/luis/battery_level"
    unit_of_measurement: '%'
    retain: true

automation:
  - alias: Alerta Para Substituir a Bateria dos Sensores
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id:
        - sensor.p_cozinha_battery_level
        - sensor.p_principal_battery_level
        - sensor.p_esquerda_battery_level
        - sensor.p_direita_battery_level
        - sensor.p_portao_battery_level
        - sensor.p_anexo_battery_level
        - sensor.p_sala_battery_level
        - sensor.p_correio_battery_level
        - sensor.p_botao_battery_level
        - sensor.p_temp1_battery_level
        - sensor.p_temp2_battery_level
        - sensor.p_inerruptor_battery_level
        - sensor.p_rua_battery_level
        - sensor.p_1andar_battery_level
        - sensor.p_portaanexo_battery_level
      below: 5
    condition:
      - condition: template
        value_template: '{{ states.input_boolean.battery_notifications.state == "on" }}'
    action:
      - service: notify.my_pushbullet
        data_template:
          message: 'Alerta! {{ trigger.from_state.attributes.friendly_name }} necessita de ser substituída, apenas tem {{ trigger.from_state.state }}% de bateria restante!!'
