#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Botões
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-06-06
#	Description :	Set configuration to botões
#--------------------------------------------------------------------

homeassistant:

automation:

# Liga / Desliga os Sonoffs com 1 click no botão esquerdo - INTERRUPTOR COZINHA - 
  - alias: 'Liga / desliga os 3 Sonoffs'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d0001e0f8b3
          click_type: single
    action:
      - service: switch.toggle
        entity_id: switch.luz_petra
      - service: switch.toggle
        entity_id: switch.telheiro
      - service: switch.toggle
        entity_id: switch.anexo_rua
      - service: switch.toggle
        entity_id: switch.luz1
      - service: switch.toggle
        entity_id: switch.luz2

# Abre / Fecha portão do carro com 1 click no botão direito - INTERRUPTOR COZINHA - 
  - alias: 'Abre portão carro - COZINHA'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_right_158d0001e0f8b3
          click_type: single
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_34ce0088aff1
          brightness: 250
          color_name: blue
      - delay: 0:00:00
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_7811dcb3556e
          brightness: 250
          color_name: blue
      - service: shell_command.portaocarro 
      - service: script.portaocarro

# Abre / Fecha portão do carro com 1 clicks no botão - INTERRUPTOR ANEXO - 
  - alias: 'Abre portão carro - ANEXO'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: single
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_34ce0088aff1
          brightness: 250
          color_name: blue
      - delay: 0:00:00
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_7811dcb3556e
          brightness: 250
          color_name: blue
      - service: shell_command.portaocarro 
      - service: script.portaocarro

      