#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Botões
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-06-06
#	Description :	Set configuration to botões
#--------------------------------------------------------------------

homeassistant:

input_boolean:

  on_off_campainha:
    name: On/Off Campainha
    initial: 'on'
    icon: 'mdi:gesture-double-tap'

automation:

# Liga / Desliga os Sonoffs com 1 click no botão esquerdo - INTERRUPTOR COZINHA - 
  - alias: 'Liga / desliga os 3 Sonoffs'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d0001e0f8b3
          click_type: single
    action:
      - service: switch.toggle
        entity_id: switch.luz_petra
      - service: switch.toggle
        entity_id: switch.telheiro
      - service: switch.toggle
        entity_id: switch.anexo_rua
      - service: switch.toggle
        entity_id: switch.luz1
      - service: switch.toggle
        entity_id: switch.luz2

# Abre / Fecha portão do carro com 1 click no botão direito - INTERRUPTOR COZINHA - 
  - alias: 'Abre portão carro - COZINHA'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_right_158d0001e0f8b3
          click_type: single
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_34ce0088aff1
          brightness: 250
          color_name: blue
      - delay: 0:00:00
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_7811dcb3556e
          brightness: 250
          color_name: blue
      - service: shell_command.portaocarro 
      - service: script.portaocarro

## CAMPAINHA UM CLICK - INTERRUPTOR PORTÃO INPUT BOOLEAN ON -

  - alias: 'Toca campainha1'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: single
    condition:
      - condition: state
        entity_id: input_boolean.on_off_campainha
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway4
          ringtone_id: 10
          ringtone_vol: 50
      - service: notify.luiszanzito
        data:
          message: "Campainha a tocar - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
          title: "Home Assistant"

  - alias: 'Toca campainha2'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: single
    condition:
      - condition: state
        entity_id: input_boolean.on_off_campainha
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10
          ringtone_vol: 50

## CAMPAINHA DOIS CLICKs - INTERRUPTOR PORTÃO INPUT BOOLEAN ON -

  - alias: 'Toca campainha3'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: double
    condition:
      - condition: state
        entity_id: input_boolean.on_off_campainha
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway4
          ringtone_id: 10
          ringtone_vol: 50
      - service: notify.luiszanzito
        data:
          message: "Campainha a tocar - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
          title: "Home Assistant"

  - alias: 'Toca campainha4'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: double
    condition:
      - condition: state
        entity_id: input_boolean.on_off_campainha
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10
          ringtone_vol: 50
          
## CAMPAINHA UM CLICK - INTERRUPTOR PORTÃO INPUT BOOLEAN OFF -

  - alias: 'Toca campainha5'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: single
    condition:
      - condition: state
        entity_id: input_boolean.on_off_campainha
        state: 'off'
    action:
      - service: notify.luiszanzito
        data:
          message: "Campainha desligada a tocar - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
          title: "Home Assistant"

## CAMPAINHA DOIS CLICKs - INTERRUPTOR PORTÃO INPUT BOOLEAN ON -

  - alias: 'Toca campainha6'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: double
    condition:
      - condition: state
        entity_id: input_boolean.on_off_campainha
        state: 'off'
    action:
      - service: notify.luiszanzito
        data:
          message: "Campainha desligada a tocar - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
          title: "Home Assistant"

      ############### DESACTIVADOS ###############

## Abre / Fecha portão do carro com 1 clicks no botão - INTERRUPTOR ANEXO - 
#  - alias: 'Abre portão carro - ANEXO'
#    trigger:
#      - platform: event
#        event_type: click
#        event_data:
#          entity_id: binary_sensor.switch_158d0001b86d3e
#          click_type: single
#    action:
#      - service: light.turn_on
#        data_template:
#          entity_id: light.gateway_light_34ce0088aff1
#          brightness: 250
#          color_name: blue
#      - delay: 0:00:00
#      - service: light.turn_on
#        data_template:
#          entity_id: light.gateway_light_7811dcb3556e
#          brightness: 250
#          color_name: blue
#      - service: shell_command.portaocarro 
#      - service: script.portaocarro
      