#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Contadores
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-03-24
#	Description :	Set configuration to Contadores
#--------------------------------------------------------------------

homeassistant:

counter:
  ccorreio:
    step: 1
  portao:
    step: 1

automation:

  - alias: Contagem correio
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d000152fc00
      to: 'on'
    action:
      - service: counter.increment
        entity_id: counter.ccorreio
        
  - alias: Contagem portao
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001d86c17
      to: 'on'
    action:
      - service: counter.increment
        entity_id: counter.portao
      
  - alias: resetar o contador
    initial_state: 'on'
    trigger:
      - platform: time
        at: '00:00:00'
    action:
      - service: counter.reset    

sensor:

  - platform: template
    sensors:
      ccorreio:
        value_template: >-
         {% if is_state('counter.ccorreio', '0') %}
          Aberta: {{ states.counter.ccorreio.state }} vezes
         {%- elif is_state('counter.ccorreio', '1') -%}
          Aberta: {{ states.counter.ccorreio.state }} vez
         {% elif states.counter.ccorreio.state | int >= 2 %}
          Aberta: {{ states.counter.ccorreio.state }} vezes
         {%- endif -%}
      portao:
        friendly_name: "Portão"
        value_template: >-
         {% if is_state('counter.portao', '0') %}
          Aberto: {{ states.counter.portao.state }} vezes
         {%- elif is_state('counter.portao', '1') -%}
          Aberto: {{ states.counter.portao.state }} vez
         {% elif states.counter.portao.state | int >= 2 %}
          Aberto: {{ states.counter.portao.state }} vezes
         {%- endif -%} 