#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Device Tracker
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-03-05
#	Description :	Set configuration to Device Tracker
#--------------------------------------------------------------------

homeassistant: 
device_tracker:

  - platform: nmap_tracker
    hosts:
      - 192.168.1.65
      - 192.168.1.68

  - platform: ping
    interval_seconds: 20
    consider_home: 60
    hosts:
      CamAnexo: 192.168.1.77
      CamTelheiro: 192.168.1.67
      CamPetra: 192.168.2.7
      CamCarolina: 192.168.1.71
      Gateway: 192.168.1.68
      RepAnexo: 192.168.1.79
      RepCasa: 192.168.1.83
#      LuisTele: 192.168.1.78
#      MonicaTele: 192.168.2.177

  - platform: bluetooth_tracker
    consider_home: 20 
    interval_seconds: 5

  - platform: mqtt_json
    devices:
     luis: zanzito/luis/location
    track_new_devices: True
    interval_seconds: 10
    consider_home: 20

  - platform: mqtt_json
    devices:
     monica: zanzito/monica/location
    track_new_devices: True
    interval_seconds: 10
    consider_home: 20

binary_sensor:    
  - platform: device_tracker_sensor
    on_state_text: sim
    off_state_text: nao 
    entities:
      - device_tracker.camanexo
      - device_tracker.camanexo_rua
      - device_tracker.camtelheiro
      - device_tracker.campetra
      - device_tracker.gateway
      - device_tracker.camcarolina
      - device_tracker.repanexo
      - device_tracker.repcasa

sensor:
  - platform: template
    sensors:
          
      luis: 
        friendly_name: 'Estado Luis'
        value_template: > 
          {%- if is_state('device_tracker.luistele', 'not_home') and is_state('device_tracker.xiaomi_mi4c', 'not_home') -%}
             Ausente
          {%- endif -%}
          {%- if is_state('device_tracker.luistele', 'home') and is_state('device_tracker.xiaomi_mi4c', 'home') -%}
             Em casa
          {%- endif -%}   
          {%- if is_state('device_tracker.luistele', 'home') and is_state('device_tracker.xiaomi_mi4c', 'not_home') -%}
             Em casa
          {%- endif -%}      
          {%- if is_state('device_tracker.luistele', 'not_home') and is_state('device_tracker.xiaomi_mi4c', 'home') -%}
             Em casa
          {%- endif -%}    
          {%- if is_state('device_tracker.luistele', 'notrabalhocampera') and is_state('device_tracker.xiaomi_mi4c', 'not_home') -%} 
             No Trabalho
          {%- endif -%}

      monica: 
        friendly_name: 'Estado Monica'
        value_template: > 
          {%- if is_state('device_tracker.androida368cde6beb22035cylon', 'not_home') and is_state('device_tracker.monicatele', 'not_home') -%}
             Ausente
          {%- endif -%}
          {%- if is_state('device_tracker.androida368cde6beb22035cylon', 'home') and is_state('device_tracker.monicatele', 'home') -%}
             Em casa
          {%- endif -%}   
          {%- if is_state('device_tracker.androida368cde6beb22035cylon', 'home') and is_state('device_tracker.monicatele', 'not_home') -%}
             Em casa
          {%- endif -%}      
          {%- if is_state('ddevice_tracker.androida368cde6beb22035cylon', 'not_home') and is_state('device_tracker.monicatele', 'home') -%}
             Em casa
          {%- endif -%}    
          {%- if is_state('device_tracker.androida368cde6beb22035cylon', 'notrabalhocampera') and is_state('device_tracker.monicatele', 'not_home') -%} 
             No Trabalho
          {%- endif -%}