#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Portões
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-02-25
#	Description :	Set configuration to Portões
#--------------------------------------------------------------------

homeassistant:
input_boolean:

  portaomota:
    name: Portão Mota
    initial: 'off'
    icon: 'mdi:motorbike'

  portaocarro:
    name: Portão Carro
    initial: 'off'
    icon: 'mdi:car-connected'

automation:

  - alias: 'portao mota'
    trigger:
      - platform: state
        entity_id: input_boolean.portaomota
        to: 'on'
    action:
      - service: shell_command.portaomota 
      - service: script.portaomota
          
  - alias: 'portao carro'
    trigger:
      - platform: state
        entity_id: input_boolean.portaocarro
        to: 'on'
    action:
      - service: shell_command.portaocarro 
      - service: script.portaocarro

# Notifica o Luis que o portão está aberto à mais de 60 min.
  - alias: Portao aberto
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001d86c17
      to: 'on'
      for:
        minutes: 60
    action:
    - service: notify.luiszanzito
      data:
        message: "Portão aberto à mais de 60 min - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
        title: "Home Assistant"
 

# Notifica o Luis que o portão está a abrir.
  - alias: Portao_aberto
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001d86c17
      to: 'on'
    action:
#      - service: mqtt.publish
#        data_template:
#          topic: zanzito/luis/say
#          payload: "Olá Luis. Portão a abrir!"
#      - delay: 00:00:10
#      - service: mqtt.publish
#        data_template:
#          topic: zanzito/luis/say
#          payload: "Espero ter cumprido a função"
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: 34:CE:00:88:AF:F1
          ringtone_id: 10007
          ringtone_vol: 10
      - service: notify.luiszanzito
        data:
          message: "Portão a abrir - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
          title: "Home Assistant"

# Notifica o Luis que o portão está fechado.
  - alias: Portao fechado
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001d86c17
      to: 'off'
    action:
#      - service: mqtt.publish
#        data_template:
#          topic: zanzito/luis/say
#          payload: "Olá Luis. Portão fechado!"
#      - delay: 00:00:20
#      - service: mqtt.publish
#        data_template:
#          topic: zanzito/luis/say
#          payload: "Espero ter cumprido a função"
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: 34:CE:00:88:AF:F1
          ringtone_id: 10008
          ringtone_vol: 10
      - service: notify.luiszanzito
        data:
          message: "Portão fechado - {{states.sensor.time.state}} - {{states.sensor.date.state}} "
          title: "Home Assistant"

script:
  
  portaomota:
    sequence:
      - delay: 00:00:01
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.portaomota

  portaocarro:
    sequence:
      - delay: 00:00:01
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.portaocarro

### CRIA UM SENSOR MAS NO PAINEL SEMPRE QUE HA ALTERAÇÃO DE ESTADO ELE NÃO FICA AMARELO - NÃO ESTÁ EM USO ###
#sensor:
#  platform: template
#  sensors:
#    door_portao:
#      value_template: '{% if is_state("binary_sensor.door_window_sensor_158d0001d86c17", "on") %} Aberto {% else %} Fechado {%- endif %}'
      
      
      