#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Portas
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-03-18
#	Description :	Set configuration to portas
#--------------------------------------------------------------------

homeassistant:
input_boolean:

  desligar_ou_ligar_portas:
    name: Portas - aberto/fechado
    initial: 'off'
    icon: 'mdi:gesture-double-tap'

automation: 

# Notifica o Luis que as portas foram abertas.
  - alias: 'Alerta de portas'
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018354d0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00015a954e
        to: 'on'
    condition: 
      - condition: state
        entity_id: input_boolean.desligar_ou_ligar_portas
        state: 'on'
    action:
      - service: notify.my_pushbullet
        data:
          message: "Porta aberta - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

# Notifica o Luis que portas ou janelas em casa abertas à mais de 30 min.
  - alias: Portas ou janelas abertas
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018354d0
        to: 'on'
        for:
          minutes: 30
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00015a954e
        to: 'on'
        for:
          minutes: 30
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d399b1
        to: 'on'
        for:
          minutes: 30
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d39ff1
        to: 'on'
        for:
          minutes: 30
    action:
      - service: notify.luiszanzito
        data_template:
          message: 'Alerta! {{ trigger.from_state.attributes.friendly_name }} está aberta à mais de 30min - {{states.sensor.time.state}}'
          title: "Home Assistant"       
#          message: 'Alerta! {{ trigger.from_state.attributes.friendly_name }} está aberta desde - {{states.sensor.date.state}} às {{states.sensor.time.state}}'
#          title: "Home Assistant"
#      data:
#        message: "Janela ou porta aberta à mais de 15 minutos - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

sensor:
  platform: template
  sensors:
    door_cozinha:
      value_template: '{% if is_state("binary_sensor.door_window_sensor_158d00018354d0", "on") %} Aberta {% else %} Fechada {%- endif %}'
    door_esquerda:
      value_template: '{% if is_state("binary_sensor.door_window_sensor_158d0001d399b1", "on") %} Aberta {% else %} Fechada {%- endif %}'
    door_direita:
      value_template: '{% if is_state("binary_sensor.door_window_sensor_158d0001d39ff1", "on") %} Aberta {% else %} Fechada {%- endif %}'      
    door_principal:
      value_template: '{% if is_state("binary_sensor.door_window_sensor_158d00015a954e", "on") %} Aberta {% else %} Fechada {%- endif %}'