#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Rua
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-04-25
#	Description :	Set configuration to Anexo
#--------------------------------------------------------------------

homeassistant:

automation:

# Liga as luzes da rua quando há movimento à noite com luminosidade abaixo dos 300.
  - alias: Liga as luzes da rua quando há movimento à noite com luminosidade abaixo dos 300.
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e51352
      to: 'on'
    condition:
      condition: numeric_state
      entity_id: sensor.illumination_158d0001e51352
      below: '300'
    action:
      - service: switch.turn_on
        entity_id: switch.luz_petra
      - service: switch.turn_on
        entity_id: switch.telheiro
      - service: switch.turn_on
        entity_id: switch.anexo_rua

# Desliga as luzes da rua 4 minutos após o ultimo movimento com luminosidade abaixo dos 300.
  - alias: Desliga as luzes da rua 4 minutos após o ultimo movimento com luminosidade abaixo dos 300.
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e51352
      to: 'off'
      for:
        minutes: 4
    condition:
      condition: numeric_state
      entity_id: sensor.illumination_158d0001e51352
      below: 300
    action:
      - service: switch.turn_off
        entity_id: switch.luz_petra
      - service: switch.turn_off
        entity_id: switch.telheiro
      - service: switch.turn_off
        entity_id: switch.anexo_rua
      - service: switch.turn_off
        entity_id: switch.luz1
      - service: switch.turn_off
        entity_id: switch.luz2

# Desliga os SONOFFs de rua durante o dia caso estejam ligados mais que 30 segundos.
  - alias: Desliga os SONOFFs de rua durante o dia caso estejam ligados mais que 30 segundos.
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.todos
        to: 'on'
        for:
          seconds: 30
    condition:
      condition: numeric_state
      entity_id: sensor.illumination_158d0001e51352
      above: 600
    action:
      - service: switch.turn_off
        entity_id: switch.luz_petra
      - service: switch.turn_off
        entity_id: switch.telheiro
      - service: switch.turn_off
        entity_id: switch.anexo_rua
      - service: switch.turn_off
        entity_id: switch.luz1
      - service: switch.turn_off
        entity_id: switch.luz2

###############################################################################
#                                                                             #
#                           D E S A T I V O S                                 #
#                                                                             #
###############################################################################
        
## Liga a luz do anexo das 07:01
#  - alias: Liga luz do anexo de manha
#    initial_state: true
#    trigger:
#      platform: time
#      at: '07:01'                         
#    action:
#      service: switch.turn_on                 
#      data:
#        entity_id: switch.anexo
#
## Desliga a luz do anexo às 19:00
#  - alias: Desliga anexo tarde
#    trigger:
#      platform: time
#      at: '18:59' 
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.anexo

#  - alias: Liga luz do anexo 5 minutos apos o nascer do sol
#    initial_state: true
#    trigger:
#      platform: sun
#      event: sunrise
#      offset: '00:05:00'                     
#    action:
#      service: switch.turn_on                 
#      data:
#        entity_id: switch.anexo
#
#  - alias: Desliga luz do anexo após por do sol
#    trigger:
#      platform: sun
#      event: sunset
#      offset: '+00:00:00'
#    condition:
#      condition: sun
#      before: sunset
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.anexo
#
#  - alias: Liga a luz á noite com o sensor de movimento.
##    initial_state: true
#    trigger:
#      platform: state
#      entity_id: binary_sensor.motion_sensor_158d0001e516b8
#      to: 'on'
#    condition:
#      condition: sun
#      after: sunset
##      before: sunrise
#    action:
#      service: switch.turn_on  
#      data:      
#        entity_id: switch.anexo
#
#  - alias: Desliga a luz do anexo após 2min sem movimento depois do por do sol e antes do nascer do sol.
##    initial_state: true
#    trigger:
#      platform: state
#      entity_id: binary_sensor.motion_sensor_158d0001e516b8
#      to: 'off'
#      for:
#        minutes: 2
#    condition:
#      condition: sun
#      after: sunset
##      before: sunrise
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.anexo    

### CRIA UM SENSOR MAS NO PAINEL SEMPRE QUE HA ALTERAÇÃO DE ESTADO ELE NÃO FICA AMARELO - NÃO ESTÁ EM USO ###
#sensor:
#  platform: template
#  sensors:
#    motion_anexo:
#      value_template: '{% if is_state("binary_sensor.motion_sensor_158d0001e516b8", "on") %} Sim {% else %} Não {%- endif %}'