#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Sala
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-02-13
#	Description :	Set configuration to sensor da sala
#--------------------------------------------------------------------

homeassistant:

sensor:
  platform: template
  sensors:
    motion_sala:
      value_template: '{% if is_state("binary_sensor.motion_sensor_158d00015e8fdf", "on") %} Sim {% else %} Não {%- endif %}'