#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Sonoff
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-08-19
#	Description :	Set configuration to Sonoff
#--------------------------------------------------------------------

#homeassistant:

switch:

# switch anexo
  - platform: mqtt
    name: "Anexo"
    state_topic: "stat/anexo/POWER"
    command_topic: "cmnd/anexo/power"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

# switch rua
  - platform: mqtt
    name: "Anexo Rua"
    state_topic: "stat/rua/POWER"
    command_topic: "cmnd/rua/power"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

# switch telheiro
  - platform: mqtt
    name: "telheiro"
    state_topic: "stat/telheiro/POWER"
    command_topic: "cmnd/telheiro/power"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    
  # switch petra Duo 1
  - platform: mqtt
    name: "Sirene"
    state_topic: "stat/Petra_Duo/POWER1"
    command_topic: "cmnd/Petra_Duo/power1"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    
  # switch petra Duo 2
  - platform: mqtt
    name: "Luz Petra"
    state_topic: "stat/Petra_Duo/POWER2"
    command_topic: "cmnd/Petra_Duo/power2"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  
  # switch PZEM
  - platform: mqtt
    name: "Pzem"
    state_topic: "stat/Pzem/POWER"
    command_topic: "cmnd/Pzem/power"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    
  # switch BH OnOfre 1
  - platform: mqtt
    name: "Luz1"
    state_topic: "stat/bhonofre/POWER1"
    command_topic: "cmnd/bhonofre/power1"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
    
  # switch BH OnOfre 2
  - platform: mqtt
    name: "Luz2"
    state_topic: "stat/bhonofre/POWER2"
    command_topic: "cmnd/bhonofre/power2"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
    
sensor:
  - platform: mqtt
    name: "Temp. rua - Petra"
    state_topic: "tele/Petra_Duo/SENSOR"
    value_template: "{{ value_json['SI7021'].Temperature }}"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Humi. rua - Petra"
    state_topic: "tele/Petra_Duo/SENSOR"
    value_template: "{{ value_json['SI7021'].Humidity }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: "Temp. Anexo"
    state_topic: "tele/anexo/SENSOR"
    value_template: "{{ value_json['SI7021'].Temperature }}"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Humi. Anexo"
    state_topic: "tele/anexo/SENSOR"
    value_template: "{{ value_json['SI7021'].Humidity }}"
    unit_of_measurement: "%"
    


###############################################################################
#                                                                             #
#                           B I N A R Y _ S E N S O R S                       #
#                                                                             #
###############################################################################  
binary_sensor:    

  - platform: mqtt
    name: "Sonoff Anexo"
    state_topic: "tele/anexo/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    
  - platform: mqtt
    name: "Sonoff Anexo Rua"
    state_topic: "tele/rua/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"

  - platform: mqtt
    name: "Sonoff Telheiro"
    state_topic: "tele/telheiro/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    
  - platform: mqtt
    name: "Sonoff Petra"
    state_topic: "tele/Petra_Duo/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"