#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - System Monitor
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-02-13
#	Description :	Set configuration to System Monitor
#--------------------------------------------------------------------

sensor:
  - platform: time_date
    display_options:
    - 'time'
    - 'date'

  - platform: api_streams
  
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
      
  - platform: template
    sensors:
      since_last_boot_templated:
        value_template: >-
          {%- if states.sensor.since_last_boot -%}
            {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
            {%- set count = slb | length -%}
            {%- set hms = slb[count - 1] -%}
            {%- set hms_split = hms.split(':') -%}
            {%- set hours = hms_split[0] | int -%}
            {%- set minutes = hms_split[1] | int -%}
            {%- if count == 3 -%}
              {%- set days = slb[0] | int -%}
            {%- else -%}
              {%- set days = 0 -%}
            {%- endif -%}
            {%- if days == 0 and hours == 0 and minutes == 0 -%}
              Menos de 1 min
            {%- else -%}
              {%- if days > 0 -%}
                {%- if days == 1 -%}
                  1 dia
                {%- else -%}
                  {{ days }} dias
                {%- endif -%}
              {%- endif -%}
              {%- if hours > 0 -%}
                {%- if days > 0 -%}
                  {{ ', ' }}
                {%- endif -%}
                {%- if hours == 1 -%}
                  1 hora
                {%- else -%}
                  {{ hours }} horas
                {%- endif -%}
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if days > 0 or hours > 0 -%}
                  {{ ', ' }}
                {%- endif -%}
                {%- if minutes == 1 -%}
                  1 min
                {%- else -%}
                  {{ minutes }} min
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- else -%}
            n/a
          {%- endif -%}

script:
          
  restart_ha:
    alias: 'Reiniciar HA'
    sequence:
      - service: homeassistant.restart
  
automation:

#Informa os utilizador que houve uma tentativa de ataque ao home assistant.          
  - alias: "Tentativa de Ataque Home Assistant"
    trigger:
      - platform: state
        entity_id: persistent_notification.httplogin
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      - service: notify.luiszanzito
        data_template:
          title: "Tentativa falhada no acesso ao Home Assistant!"
          message: "{{ states.persistent_notification.httplogin.attributes.message }}"
          data:
            url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.httplogin.attributes.message.split("from ") [1]}}
