#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Portões
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-03-06
#	Description :	Set configuration to Portões
#--------------------------------------------------------------------

homeassistant:

automation:

# Liga a luz do telheiro, da rua e da Petra às 04:15
  - alias: Liga Telheiro e petra
    trigger:
      platform: time
      at: '04:15'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.telheiro
      - service: switch.turn_on
        data:
          entity_id: switch.petra
      - service: switch.turn_on
        data:
          entity_id: switch.anexo_rua

# Desliga a luz do telheiro, da rua e da Petra às 04:39
  - alias: Desliga telheiro e petra
    trigger:
      platform: time
      at: '04:39' 
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.telheiro
      - service: switch.turn_off
        data:
          entity_id: switch.petra
      - service: switch.turn_off
        data:
          entity_id: switch.anexo_rua
          
# Liga / Desliga os 3 Sonoffs com 1 click no botão
  - alias: 'Liga / desliga os 3 Sonoffs'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: single
    action:
      - service: switch.toggle
        entity_id: switch.petra
      - service: switch.toggle
        entity_id: switch.telheiro
      - service: switch.toggle
        entity_id: switch.anexo_rua

# Abre / Fecha portão do carro com 2 clicks no botão
  - alias: 'Abre portão carro'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: double
    action:
      - service: shell_command.portaocarro 
      - service: script.portaocarro

# Ativa / Desativa tomada 220V xiaomi
  - alias: 'Ativa / Desativa tomada 220V xiaomi'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_both_158d0001e0f91d
          click_type: both
    action:
      - service: switch.toggle 
        entity_id: switch.plug_158d00015e8107

switch:

# switch petra
- platform: mqtt
  name: "petra"
  state_topic: "stat/petra/POWER"
  command_topic: "cmnd/petra/power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

# switch telheiro
- platform: mqtt
  name: "telheiro"
  state_topic: "stat/telheiro/POWER"
  command_topic: "cmnd/telheiro/power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true