#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Telheiro
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-09-20
#	Description :	Set configuration to Telheiro
#--------------------------------------------------------------------

homeassistant:

input_datetime:
  luz1:
    name: ON Sonoffs Ext.
    has_time: true      
    initial: '05:20:00'
  luz2:
    name: OFF Sonoffs Ext.
    has_time: true      
    initial: '05:39:00'

automation:

  - alias: Liga Rua / Telheiro / Petra
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.luz1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.telheiro
      - service: switch.turn_on
        data:
          entity_id: switch.luz_petra
      - service: switch.turn_on
        data:
          entity_id: switch.anexo_rua
      - service: switch.turn_on
        data:
          entity_id: switch.luz1
      - service: switch.turn_on
        data:
          entity_id: switch.luz2
          
  - alias: Desliga Anexo / Telheiro / Petra
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.luz2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.telheiro
      - service: switch.turn_off
        data:
          entity_id: switch.luz_petra
      - service: switch.turn_off
        data:
          entity_id: switch.anexo_rua
      - service: switch.turn_off
        data:
          entity_id: switch.luz1
      - service: switch.turn_off
        data:
          entity_id: switch.luz2

###############################################################################
#                                                                             #
#                           D E S A T I V O S                                 #
#                                                                             #
###############################################################################

## Liga a luz do telheiro, da rua e da Petra às 04:15
#  - alias: Liga Telheiro e petra
#    trigger:
#      platform: time
#      at: '04:15'
#    action:
#      - service: switch.turn_on
#        data:
#          entity_id: switch.telheiro
#      - service: switch.turn_on
#        data:
#          entity_id: switch.luz_petra
#      - service: switch.turn_on
#        data:
#          entity_id: switch.anexo_rua
#
## Desliga a luz do telheiro, da rua e da Petra às 04:39
#  - alias: Desliga telheiro e petra
#    trigger:
#      platform: time
#      at: '04:39' 
#    action:
#      - service: switch.turn_off
#        data:
#          entity_id: switch.telheiro
#      - service: switch.turn_off
#        data:
#          entity_id: switch.luz_petra
#      - service: switch.turn_off
#        data:
#          entity_id: switch.anexo_rua