#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Portões
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-02-11
#	Description :	Set configuration to Portões
#--------------------------------------------------------------------

homeassistant:
automation:

#Liga a luz do Telheiro e da Petra às 04:15
  - alias: Liga Telheiro e petra
    trigger:
      platform: time
      at: '04:15'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.telheiro
      - service: switch.turn_on
        data:
          entity_id: switch.petra
      - service: switch.turn_on
        data:
          entity_id: switch.anexo_fora

#Desliga a luz do Telheiro e da Petra às 04:40
  - alias: Desliga telheiro e petra
    trigger:
      platform: time
      at: '04:39' 
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.telheiro
      - service: switch.turn_off
        data:
          entity_id: switch.petra
      - service: switch.turn_off
        data:
          entity_id: switch.anexo_fora

switch:

#switch petra
- platform: mqtt
  name: "petra"
  state_topic: "stat/petra/POWER"
  command_topic: "cmnd/petra/power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

#switch telheiro
- platform: mqtt
  name: "telheiro"
  state_topic: "stat/telheiro/POWER"
  command_topic: "cmnd/telheiro/power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true


###############################################################################
#                                                                             #
#                           D E S A T I V O S                                 #
#                                                                             #
###############################################################################

#Liga a luz do telheiro às 17:30
#  - alias: Liga telheiro tarde
#    trigger:
#      platform: time
#      at: '17:29'
#    action:
#      service: switch.turn_on
#      data:
#        entity_id: switch.telheiro

#Desliga a luz do telheiro às 22:30
#  - alias: Desliga telheiro tarde
#    trigger:
#      platform: time
#      at: '22:29' 
#    action:
#      service: switch.turn_off
#      data:
#        entity_id: switch.telheiro 