homeassistant:

automation:

############################################################# TESTE##########################################
  - alias: Alarme auto1
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d86c17
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.auto_alarme
        state: 'on'
      - condition: state
        entity_id: sensor.luis
        state: 'Em casa'
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'        
    action:
      - service: script.alarmepromimityoff
      - delay: 0:00:05
      - service: homeassistant.turn_off            
        entity_id: switch.plug_158d00015e8107