#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Weather
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-03-05
#	Description :	Set configuration to Weather
#--------------------------------------------------------------------
homeassistant:

sensor:
  - platform: darksky
    api_key: !secret key_weather
    language: pt
    monitored_conditions:
      - summary
      - precip_type
      - precip_probability
      - temperature
      - humidity
      - temperature_max
      - temperature_min
      - hourly_summary
      - daily_summary

#  - platform: yr
#    name: Weather
#    forecast: 24
#    monitored_conditions:
#      - temperature
#      - symbol
#      - precipitation
#      - windSpeed
#      - pressure
#      - windDirection
#      - humidity
#      - fog
#      - cloudiness
#      - lowClouds
#      - mediumClouds
#      - highClouds
#      - dewpointTemperature
#
#  - platform: template
#    sensors:
#     #Estado do Tempo
#      estadodotempo:
#        friendly_name: 'Ceu'
#        value_template: > 
#          {%- if is_state('sensor.dark_sky_summary', 'Partly Cloudy') -%}
#            Parcialmente Nublado
#          {%- elif is_state('sensor.dark_sky_summary', 'Clear') -%}
#            Limpo
#          {%- elif is_state('sensor.dark_sky_summary', 'Light Rain and Breezy') -%}
#            Aguaceiros e vento fraco
#          {%- elif is_state('sensor.dark_sky_summary', 'Light Rain') -%}
#            Aguaceiros
#          {%- elif is_state('sensor.dark_sky_summary', 'Rain') -%}
#            Chuvoso
#          {%- elif is_state('sensor.dark_sky_summary', 'Mostly Cloudy') -%}    
#            Muito Nublado
#          {%- elif is_state('sensor.dark_sky_summary', 'Drizzle') -%}    
#            Chuviscos
#          {%- elif is_state('sensor.dark_sky_summary', 'Overcast') -%}    
#            Nublado
#          {%- elif is_state('sensor.dark_sky_summary', 'Breezy and Overcast') -%}    
#            Vento e nublado
#          {%- elif is_state('sensor.dark_sky_summary', 'Rain and Breezy') -%}    
#            Chuva e vento
#          {%- elif is_state('sensor.dark_sky_summary', 'Rain and Windy') -%}    
#            Chuva e vento
#          {%- elif is_state('sensor.dark_sky_summary', 'Breezy and Mostly Cloudy') -%}    
#            Vento fraco e muitas nuvens
#          {%- elif is_state('sensor.dark_sky_summary', 'Breezy and Partly Cloudy') -%}    
#            Vento fraco e algumas nuvens
#          {%- elif is_state('sensor.dark_sky_summary', 'Breezy') -%}    
#            Vento fraco            
#          {%- endif -%}

automation:

# Informa o Luis da temperatura do quarto da Carolina e o estado do tempo na rua.
  - alias: Estado do tempo
    initial_state: true
    trigger:
      platform: time
      at: '04:10:00'
    action:
      service: notify.my_pushbullet
      data:
        message: "Bom dia , estão {{ states.sensor.temperature_158d0001ab1740.state}} graus no quarto da Carolina. Hoje o céu está {{ states.sensor.estadodotempo.state }} e estão neste momento {{ states.sensor.temperature_158d0001fa763c.state }} graus e {{ states.sensor.dark_sky_humidity.state }}% de humidade. A temperatura máxima vai ser de {{ states.sensor.dark_sky_daily_high_temperature.state }} graus e {{ states.sensor.dark_sky_daily_low_temperature.state }} graus de mínima. Existe {{ states.sensor.dark_sky_precip_probability.state }}% de probabilidade de chover hoje.{% if states('sensor.dark_sky_precip_probability') | int > 50 %} Não te esqueças de levar o chapéu de chuva. Tem um bom dia chuvoso ;){% else %} Tem um bom dia.{% endif %}"
        title: "Home Assistant"

# Informa o Luis da probabilidade de chuva para o dia seguinte.
  - alias: Chove Amanhã
    hide_entity: true
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      - condition: numeric_state
        entity_id: sensor.dark_sky_precip_probability
        above: '20'
    action:
      service: notify.my_pushbullet
      data:
        message: "Há {{ states.sensor.dark_sky_precip_probability.state }}% de probabilidadede chover amanhã."