#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Gateway
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-03-06
#	Description :	Set configuration to Gateway
#--------------------------------------------------------------------

homeassistant:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: 192.168.2.45
      mac: !secret key_gateway2
      key: !secret key_gateway1

input_boolean:

  proximity:
    name: Alarme Proximity - On/Off
    initial: 'off'
    icon: 'mdi:gesture-double-tap'

automation:

### ALARME COM PROXIMITY ###
  - alias: 'Play xiaomi sounds'
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018354d0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015e8fdf
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00015a954e
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d399b1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d39ff1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015b1c11
        to: 'on'
#      - platform: numeric_state
#        entity_id: proximity.luis_casa
#        above: 10
    condition:
      - condition: state
        entity_id: input_boolean.proximity
        state: 'on'
    action:
      service: script.alarme

################################################
#                      BOTÕES                  #
################################################      

# Liga alarme com o interruptor de 2 botões
  - alias: 'Liga alarme'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d0001e0f91d
          click_type: single
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 10
      - delay: 0:00:01
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10009
          ringtone_vol: 17
      - service: script.atraso

# Desliga o SCRIPT do alarme e o alarme com o interruptor de 2 botões
  - alias: 'desliga alarme'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_right_158d0001e0f91d
          click_type: single
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 10
      - delay: 0:00:01
      - service: script.turn_off
        data:
          entity_id: script.atraso
      - service: script.turn_off
        data:
          entity_id: script.alarme
      - service: notify.luiszanzito
        data:
          message: "Alarme desativo por EMERGENCIA - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
      - delay: 0:00:01
      - service: homeassistant.turn_off
        entity_id: input_boolean.proximity
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret key_gateway2
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10006
          ringtone_vol: 17

script:
  
  atraso:
    sequence:
      - delay: 0:15:00
      - service: homeassistant.turn_on
        entity_id: input_boolean.proximity
      - service: notify.luiszanzito
        data:
          message: "Alarme ativo - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

  alarme:
    sequence:
      - delay: 0:00:01
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 7
      - delay: 0:00:20
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - service: notify.luiszanzito
        data:
          message: "Alarme a tocar em casa - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
      - delay: 0:00:25
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - delay: 0:00:25
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - delay: 0:00:25
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
          
sensor:

  - platform: template
    sensors:
      proximity:
        friendly_name: 'Estado do alarme:'
        value_template: >
            {%- if is_state("input_boolean.proximity", "on") -%}
              Ligado
             {% else %}
              Desligado
            {% endif %}