#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Gateway
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-04-29
#	Description :	Set configuration to Gateway
#--------------------------------------------------------------------

homeassistant:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: 192.168.1.75
      mac: !secret key_gateway2
      key: !secret key_gateway1
    - host: 192.168.1.99
      mac: !secret key_gateway4
      key: !secret key_gateway3

input_boolean:

  proximity:
    name: Alarme - On/Off
    initial: 'off'
    icon: 'mdi:gesture-double-tap'

automation:

### ALARME COM PROXIMITY ###
  - alias: 'Play xiaomi sounds'
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018354d0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015e8fdf
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00015a954e
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d399b1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d39ff1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001b91cef
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001e53332
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.proximity
        state: 'on'
    action:
      service: script.alarme

# Acende LED quando o alarme está ligado.
  - alias: Alarme ligado
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.proximity
      to: 'on'
    action:
      - service: homeassistant.turn_on                
        entity_id: switch.plug_158d00015e8107

# Apaga LED quando o alarme está desligado.
  - alias: Alarme ligado
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.proximity
      to: 'off'
    action:
      - service: homeassistant.turn_off            
        entity_id: switch.plug_158d00015e8107

# Notifica se portas ou janelas estão abertas quando ligo o alarme.
  - alias: 'Notificador de portas janelas abertas'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: script.atraso
      from: 'off'
      to: 'on'
    condition:
      condition: state
      entity_id: group.sensoresportajanela
      state: 'on'
    action:
      - service: notify.my_pushbullet
        data:
          title: "Home Assistant"
          message: >
           {%- if states.binary_sensor.door_window_sensor_158d00018354d0.state  == "on" -%}
           {% if doors | trim != "" %}
           {%- set doors = doors ~ "a porta cozinha " -%}
           {% else %}
           {%- set doors = doors ~ "porta cozinha " -%}
           {% endif %}
           {%- endif -%}
                
           {%- if states.binary_sensor.door_window_sensor_158d0001d399b1.state  == "on" -%}
           {% if doors | trim != "" %}
           {%- set doors = doors ~ "a porta esquerda " -%}
           {% else %}
           {%- set doors = doors ~ "porta esquerda " -%}
           {% endif %}
           {%- endif -%}  
           
           {%- if states.binary_sensor.door_window_sensor_158d0001d39ff1.state == "on" -%}
           {% if doors | trim != "" %}
           {%- set doors = doors ~ "a porta direita " -%}
           {% else %}
           {%- set doors = doors ~ "porta direita " -%}
           {% endif %}
           {%- endif -%}
           
           {%- if states.binary_sensor.door_window_sensor_158d00015a954e.state == "on"  -%}
           {% if doors | trim != "" %}
           {%- set doors = doors ~ "a porta principal " -%}
           {% else %}
           {%- set doors = doors ~ "porta principal " -%}
           {% endif %}
           {%- endif -%}
           A/s {{ doors}} {%- if 'a' in doors -%} estão {%- else %} está {%- endif %} aberta/s. O Alarme não pode ser ativo.

###############################################################################
# Alerta após 20 minutos sem ninguem estar em casa e que o alarme está desactivo
###############################################################################

  - alias: Home Security System WatchDog 20 minutes
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.proximity
        to: 'off'
        for: 
          minutes: 20
    condition:
      - condition: state
        entity_id: sensor.luis
        state: 'Ausente'
      - condition: state
        entity_id: sensor.monica
        state: 'Ausente'
    action:
      - service: notify.my_pushbullet
        data:
          message: "Ninguem em casa á 20 min. Ativar alarme. - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

################################################
#                      BOTÕES                  #
################################################      

# Liga alarme com o interruptor de 2 botões
  - alias: 'Liga alarme'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d0001e0f91d
          click_type: single
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 10
      - delay: 0:00:01
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10010
          ringtone_vol: 17
      - service: script.atraso

# Desliga o SCRIPT do alarme e o alarme com o interruptor de 2 botões
  - alias: 'desliga alarme - COZINHA'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_right_158d0001e0f91d
          click_type: single
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 10
      - service: switch.turn_off
        data:
          entity_id: switch.sirene
      - delay: 0:00:01
      - service: script.turn_off
        data:
          entity_id: script.atraso
      - service: script.turn_off
        data:
          entity_id: script.alarme
      - service: notify.my_pushbullet
        data:
          message: "Alarme desativado MANUALMENTE na cozinha - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
      - delay: 0:00:01
      - service: homeassistant.turn_off
        entity_id: input_boolean.proximity
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret key_gateway2
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10006
          ringtone_vol: 17
          
# Desliga o SCRIPT do alarme e o alarme no botão - INTERRUPTOR ANEXO - 
  - alias: 'desliga alarme - ANEXO'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: double
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 10
      - service: switch.turn_off
        data:
          entity_id: switch.sirene
      - delay: 0:00:01
      - service: script.turn_off
        data:
          entity_id: script.atraso
      - service: script.turn_off
        data:
          entity_id: script.alarme
      - service: notify.my_pushbullet
        data:
          message: "Alarme desativado MANUALMENTE no anexo - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
      - delay: 0:00:01
      - service: homeassistant.turn_off
        entity_id: input_boolean.proximity
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret key_gateway2
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10006
          ringtone_vol: 17

script:

  atraso:
    sequence:
      - delay: 0:05:00
      - service: homeassistant.turn_on
        entity_id: input_boolean.proximity
      - service: notify.my_pushbullet
        data:
          message: "Alarme ativo - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

  alarme:
    sequence:
      - delay: 0:00:01
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 7
      - delay: 0:00:10
      - service: switch.turn_on
        data:
          entity_id: switch.sirene
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway4
          ringtone_id: 1
          ringtone_vol: 100
      - service: notify.my_pushbullet
        data:
          message: "Alarme a tocar em casa - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
      - delay: 0:00:25
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway4
          ringtone_id: 1
          ringtone_vol: 100
      - delay: 0:00:25
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway4
          ringtone_id: 1
          ringtone_vol: 100
      - delay: 0:00:25
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway4
          ringtone_id: 1
          ringtone_vol: 100
      - delay: 0:05:00
      - service: switch.turn_off
        data:
          entity_id: switch.sirene
          
  alarmeoff:
    sequence:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10001
          ringtone_vol: 10
      - service: switch.turn_off
        data:
          entity_id: switch.sirene
      - delay: 0:00:01
      - service: script.turn_off
        data:
          entity_id: script.atraso
      - service: script.turn_off
        data:
          entity_id: script.alarme
      - service: notify.my_pushbullet
        data:
          message: "Alarme desativado pelo telemovel - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
      - delay: 0:00:01
      - service: homeassistant.turn_off
        entity_id: input_boolean.proximity
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret key_gateway2
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret key_gateway4
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10006
          ringtone_vol: 17

  alarmeon:
    sequence:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 10010
          ringtone_vol: 17
      - delay: 0:05:00
      - service: homeassistant.turn_on
        entity_id: input_boolean.proximity
      - delay: 0:00:01
      - service: notify.my_pushbullet
        data:
          message: "Alarme ativo - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

sensor:

  - platform: template
    sensors:
      proximity:
        friendly_name: 'Estado do alarme:'
        value_template: >
            {%- if is_state("input_boolean.proximity", "on") -%}
              Ligado
             {% else %}
              Desligado
            {% endif %}

group:

  sensoresportajanela:
    name: notificaportasjanelas
    entities:
      - binary_sensor.door_window_sensor_158d00018354d0
      - binary_sensor.door_window_sensor_158d0001d399b1 
      - binary_sensor.door_window_sensor_158d0001d39ff1 
      - binary_sensor.door_window_sensor_158d00015a954e