#--------------------------------------------------------------------
#         _   _        ____      _____  _     ______      ______ 
#       | \ | |      / __ \    |  __ \| |   |  ____|    |  ____|
#       |  \| | ___ | |  | |___| |__) | |__ | |__   _ __| |__   
#       | . ` |/ _ \| |  | / __|  ___/| '_ \|  __| | '__|  __|  
#       | |\  | (_) | |__| \__ \ |    | | | | |____| |  | |____ 
#       |_| \_|\___/ \____/|___/_|    |_| |_|______|_|  |______|
#
#	Home Assistant - Gateway
#--------------------------------------------------------------------
#	Author		:	Luis Belo
#	Date		:	2018-02-18
#	Description :	Set configuration to Gateway
#--------------------------------------------------------------------

homeassistant:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
   - host: 192.168.2.45
     mac: !secret key_gateway2
     key: !secret key_gateway1

group:
  my_gateway:
    name: My Gateway
    entities:
#     - input_boolean.mute_gateway_sounds
#     - input_select.gateway_sound
#     - input_number.gateway_volume
#     - input_number.loop_delay
#     - script.play_sel_sound
#     - script.play_sel_sound_loop
#     - script.play_sel_sound_single

input_boolean:
    
  desligar_ou_ligar_alarme:
    name: Alarme tracker - On/Off
    initial: 'off'
    icon: 'mdi:gesture-double-tap'
    
  desligar_ou_ligar_alarme_on:
    name: Alarme - On/Off
    initial: 'off'
    icon: 'mdi:gesture-double-tap'

automation:

###############################################################################
#                                                                             #
#                           ALARME COM DEVICE TRACKER                         #
#                                                                             #
###############################################################################  

  - alias: 'Play xiaomi sounds'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018354d0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015e8fdf
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00015a954e
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d399b1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d39ff1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015b1c11
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.desligar_ou_ligar_alarme
        state: 'on'
      - condition: state
        entity_id: sensor.luis
        state: 'Ausente'
      - condition: state
        entity_id: sensor.monica
        state: 'Ausente'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
#      - service: homeassistant.turn_on                
#        entity_id: switch.plug_158d00015e8107 
      - service: notify.my_pushbullet
        data:
          message: "Alarme a tocar em casa - {{states.sensor.date.state}} às {{states.sensor.time.state}}"

###############################################################################
#                                                                             #
#                           ALARME SEM DEVICE TRACKER                         #
#                                                                             #
############################################################################### 

  - alias: 'Play xiaomi sounds'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018354d0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015e8fdf
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00015a954e
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d399b1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001d39ff1
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00015b1c11
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.desligar_ou_ligar_alarme_on
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret key_gateway2
          ringtone_id: 1
          ringtone_vol: 100
      - service: notify.my_pushbullet
        data:
          message: "Alarme a tocar em casa - {{states.sensor.date.state}} às {{states.sensor.time.state}}"
#      - service: homeassistant.turn_on                
#        entity_id: switch.plug_158d00015e8107
#      - delay: 00:00:10
#      - service: homeassistant.turn_off               
#        entity_id: switch.plug_158d00015e8107

################################################
#                   BOTÃO XIAOMI               #
################################################

  - alias: 'Liga / desliga os 3 Sonoffs'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: single
    action:
      - service: switch.toggle
        entity_id: switch.petra
      - service: switch.toggle
        entity_id: switch.telheiro
      - service: switch.toggle
        entity_id: switch.anexo_rua

  - alias: 'Abre portão carro'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001b86d3e
          click_type: double
    action:
      - service: shell_command.portaocarro 
      - service: script.portaocarro

#  - alias: 'Desativa a sirene'
#    trigger:
#      - platform: event
#        event_type: click
#        event_data:
#          entity_id: binary_sensor.switch_158d000xxxxxc2
#          click_type: long_click_press
#    action:
#      - service: homeassistant.turn_off 
#      - entity_id: switch.plug_158d00015e8107